version: "3.8"
services:
  postgres:
    image: postgres:12.20-bullseye
    container_name: postgres_connextion_api_rest
    restart: always
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
